---
# tasks file for myloadbalancer

- name: "configure lb "
  package:
    name: "haproxy"
    state: present

- template:
    dest: "/etc/haproxy/haproxy.cfg"
    src: "haproxy.cfg.j2"
   

- service:
    name: "haproxy"
    state: restarted


